version: '3.4'

services:
  proxy:
    image: proxy
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: proxy
    ports:
      - 8080:8080
    environment:
      - WDB_RETRO_CLUSTER=o
      - WDB_RETRO_TOKEN=0
      - PROXY_PORT=8080
      - WDB_RETRO_URL=localhost

